services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adoptme-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - adoptme-network 
    volumes:
      - .:/usr/src/app
    command: sh -c "bunx prisma db push && bunx prisma generate && bun run dev"
  
  adoptme-postgres:
    image: postgres:16
    container_name: adoptme-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - adoptme-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  s3.services:
    image: prakasitj/s3-mobile-service:latest
    container_name: s3-mobile-service
    ports:
      - "9000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_S3_FORCE_PATH_STYLE=${AWS_USE_PATH_STYLE_ENDPOINT}
    networks:
      - adoptme-network

networks:
  adoptme-network:
    external: true

volumes:
  postgres-data: